let src={
    users:[],
    userList:[],
    votes:[],
    characters:[
        {
            index:1,
            name:'Lyn',
            game: 7,
            charVotes:[]
        },
        {
            index:2,
            name:'Kent',
            game: 7,
            charVotes:[]
        },
        {
            index:3,
            name:'Sain',
            game:7,
            charVotes:[]
        },
        {
            index:4,
            name:'Florina',
            game:7,
            charVotes:[]
        },
        {
            index:5,
            name:'Wil',
            game:7,
            charVotes:[]
        },
        {
            index:6,
            name:'Dorcas',
            game:7,
            charVotes:[]
        },
        {
            index:7,
            name:'Serra',
            game:7,
            charVotes:[]
        },
        {
            index:8,
            name:'Erk',
            game:7,
            charVotes:[]
        },
        {
            index:9,
            name:'Rath',
            game:7,
            charVotes:[]
        },
        {
            index:10,
            name:'Matthew',
            game:7,
            charVotes:[]
        },
        {
            index:11,
            name:'Nils',
            game:7,
            charVotes:[]
        },
        {
            index:12,
            name:'Lucius',
            game:7,
            charVotes:[]
        },
        {
            index:13,
            name:'Wallace',
            game:7,
            charVotes:[]
        },
        {
            index:14,
            name:'Eliwood',
            game:7,
            charVotes:[]
        },
        {
            index:15,
            name:'Marcus',
            game:7,
            charVotes:[]
        },
        {
            index:16,
            name:'Lowen',
            game:7,
            charVotes:[]
        },
        {
            index:17,
            name:'Bartre',
            game:7,
            charVotes:[]
        },
        {
            index:18,
            name:'Rebecca',
            game:7,
            charVotes:[]
        },
        {
            index:19,
            name:'Hector',
            game:7,
            charVotes:[]
        },
        {
            index:20,
            name:'Oswin',
            game:7,
            charVotes:[]
        },
        {
            index:21,
            name:'Guy',
            game:7,
            charVotes:[]
        },
        {
            index:22,
            name:'Merlinus',
            game:7,
            charVotes:[]
        },
        {
            index:23,
            name:'Priscilla',
            game:7,
            charVotes:[]
        },
        {
            index:24,
            name:'Raven',
            game:7,
            charVotes:[]
        },
        {
            index:25,
            name:'Canas',
            game:7,
            charVotes:[]
        },
        {
            index:26,
            name:'Dart',
            game:7,
            charVotes:[]
        },
        {
            index:27,
            name:'Fiora',
            game:7,
            charVotes:[]
        },
        {
            index:28,
            name:'Legault',
            game:7,
            charVotes:[]
        },
        {
            index:29,
            name:'Ninian',
            game:7,
            charVotes:[]
        },
        {
            index:30,
            name:'Isadora',
            game:7,
            charVotes:[]
        },
        {
            index:31,
            name:'Heath',
            game:7,
            charVotes:[]
        },
        {
            index:32,
            name:'Hawkeye',
            game:7,
            charVotes:[]
        },
        {
            index:33,
            name:'Heath',
            game:7,
            charVotes:[]
        },
        {
            index:34,
            name:'Pent',
            game:7,
            charVotes:[]
        },
        {
            index:35,
            name:'Louise',
            game:7,
            charVotes:[]
        },
        {
            index:36,
            name:'Karel',
            game:7,
            charVotes:[]
        },
        {
            index:37,
            name:'Harken',
            game:7,
            charVotes:[]
        },
        {
            index:38,
            name:'Nino',
            game:7,
            charVotes:[]
        },
        {
            index:39,
            name:'Jaffar',
            game:7,
            charVotes:[]
        },
        {
            index:40,
            name:'Vaida',
            game:7,
            charVotes:[]
        },
        {
            index:41,
            name:'Renault',
            game:7,
            charVotes:[]
        },
        {
            index:42,
            name:'Athos',
            game:7,
            charVotes:[]
        },
        
    ],
    
}

let inserts={
    addUser:(us,pwd)=>{src.users.push({username:us,password:pwd,userVotes:[]}); src.userList.push(us);},
    addVote:(us,ch,val,comm)=>{
        let a=true;
        for(let i=0;i<src.characters[ch-1].charVotes.length;i++){
            if(src.votes[src.characters[ch-1].charVotes[i]].user===us){
                a=false;
                src.votes[src.characters[ch-1].charVotes[i]].value=val;
                src.votes[src.characters[ch-1].charVotes[i]].comment=comm;
                i=src.characters[ch-1].charVotes.length;
            }
        }
        if(a){
        let index=src.userList.indexOf(us);
        src.users[index].userVotes.push(src.votes.length);
        src.characters[ch-1].charVotes.push(src.votes.length);
        src.votes.push({index:src.votes.length,user:us,character:ch,value:val,comment:comm});
        }

    }
}

module.exports={src,inserts};